//====================================================================
//
// Application: Air Dash
// Class:       Task
// Description:
//   This class implements the run method of TimerTask and updates
// the Shared singleton data. It is triggered by a timer in ActMain.
//
//====================================================================

package edu.wayne.airdash;

// Imports automatically generated by intelliJ
import java.util.Random;
import java.util.TimerTask;

//----------------------------------------------------------------
// class Task
//----------------------------------------------------------------
public class Task extends TimerTask {

    //----------------------------------------------------------------
    // run: updating data in Shared
    //----------------------------------------------------------------
    @Override
    public void run() {
        Shared data = Shared.DATA;

        // Incrementing the clock and updating controls based on inputs
        data.clock++;
        data.ordersQd += data.orderRate;
        if (data.dlvTime > 0 && data.clock % data.dlvTime == 0) {
            data.ordersQd = Math.max(data.ordersQd - data.dronesFlying, 0);
            data.ordersDlv += data.dronesFlying;
        }

        // Generating random number for drone crashes
        int randomNum = new Random().nextInt(100) + 1;
        if (data.dronesFlying > randomNum) {
            data.dronesAvl = Math.max(data.dronesAvl - 1, 0);
            data.dronesCrashed++;
        }

        // Sending message to update the screen
        ActMain.timerTaskHandler.sendEmptyMessage(0);
    }
}
