//====================================================================
//
// Application: Veritable Vittles
// Class:       Task
// Description:
//   This class implements the run method of TimerTask and updates
// the Shared singleton data. It is triggered by a timer in ActMain.
//
//====================================================================

package edu.wayne.veritablevittles;

// Imports automatically generated by intelliJ
import java.util.Random;
import java.util.TimerTask;

//----------------------------------------------------------------
// class Task
//----------------------------------------------------------------
public class Task extends TimerTask {
    //----------------------------------------------------------------
    // run: updating data in Shared
    //----------------------------------------------------------------
    @Override
    public void run() {
        Shared data = Shared.DATA;
        Random random = new Random();
        int rand = random.nextInt(3) + 1;

        // decrementing the wait time by a random number between 1 and 3; updating message
        data.time = Math.max(data.time - rand, 0);
        if (data.time == 1)
            data.message = "Your wait time is " + 1 + " minute.";
        else
            data.message = "Your wait time is " + data.time + " minutes.";

        // invoking message handler
        ActMain.timerTaskHandler.sendEmptyMessage(0);
    }
}
